// src/app/models/fuel-cost-record.model.ts
export interface FuelCostRecord {
    id?: number;            // Optional for new records; auto-generated by IndexedDB
    distance: number;      // Distance traveled
    average: number;       // Fuel average (e.g., km/liter)
    fuelPrice: number;     // Price per liter of fuel
    totalCost: number;     // Calculated total fuel cost
    date: string;          // Timestamp of the calculation
    fuelType: string;      // Fuel type
  }
  