// src/app/models/fuel-cost-record.model.ts
export interface FuelCostRecord {
    id?: number;            // Optional for new records; auto-generated by IndexedDB
    distance?: number;      // Distance traveled (for vehicle calculations)
    average?: number;       // Fuel average (e.g., km/liter for vehicle, or avg per hour for machinery)
    fuelPrice?: number;     // Price per liter of fuel
    totalCost: number;     // Calculated total cost
    date: string;          // Timestamp of the calculation
    fuelType: string;      // Fuel type or machinery type (PETROL, JCB, etc.)
    totalHours?: number;   // Total hours (for machinery calculations)
    fuelAvgPerHour?: number; // Fuel average per hour (for machinery)
    calculationType?: string; // Type of calculation (FUEL_COST, WORKED_HOURS, HOUR_WISE_COST, FERA_COST)
    startTime?: string;    // Start time (for worked hours)
    endTime?: string;      // End time (for worked hours)
    breakTime?: number;    // Break time in minutes (for worked hours)
    totalWorkedHours?: string | number; // Total worked hours (can be formatted string or number)
    hourlyRate?: number;   // Hourly rate (for hour wise cost)
    distanceKm?: number;   // Distance in km (for fera cost)
    costPerKm?: number;    // Cost per km (for fera cost)
    fuelQuantity?: number; // Fuel quantity in liters (for fuel quantity price calculator)
    liters?: number;       // Calculated liters (for fuel quantity calculator)
    totalRange?: number;   // Calculated range in km (for range calculator)
    hours?: number;        // Calculated hours (for time calculator)
    minutes?: number;      // Calculated minutes (for time calculator)
    seconds?: number;      // Calculated seconds (for time calculator)
    title?: string;        // Custom title for the record
    name?: string;         // Optional name field
    villageName?: string;  // Optional village name field
    mobile?: string;       // Optional mobile number field
    notes?: string;        // Optional notes field
  }
